version: '3.9'

services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu-database
    ports:
      - "3307:3306"
    volumes:
      - sgu-volume:/var/lib/mysql
    networks:
      - sgu-net
    restart: unless-stopped

  backend:
    build:
      context: ./server
    image: server:1.0-sgu
    container_name: sgu-backend
    environment:
      - SERVER_PORT=8080
      - DB_HOST=sgu-database
      - DB_PORT=3306
      - DB_NAME=sgu-database
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /sgu-api
    image: client:1.0-sgu
    container_name: sgu-frontend
    ports:
      - "3000:80"
    networks:
      - sgu-net
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sgu-volume:

networks:
  sgu-net:
